CREATE TABLE "GCG_6984_PRE_PRINT" (
 "GS_USER" CHAR(8),
 "PO" CHAR(7),
 "PO_LINE" CHAR(4),
 "WO" CHAR(7),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "PRINT_DATE" CHAR(8),
 "PART" CHAR(20),
 "PRINT_TIME" CHAR(8) );
